const seedData = [{"email":"sfearnley0@twitpic.com","username":"hfayre0","password":"h9J7Dy"},
{"email":"dremer1@eepurl.com","username":"ekunzler1","password":"JhiQ4F2"},
{"email":"umuckersie2@bloglines.com","username":"cdeetlefs2","password":"AdyHJQqtMOdq"},
{"email":"nciotto3@ameblo.jp","username":"cpavlenko3","password":"w0Ujb6z"},
{"email":"mduthie4@bluehost.com","username":"rcrowe4","password":"aUvw6jAFgq"},
{"email":"elorkins5@uol.com.br","username":"ghaglinton5","password":"Mmdky7"},
{"email":"cbenini6@vimeo.com","username":"zconichie6","password":"MsK6K9sg"},
{"email":"shissett7@slashdot.org","username":"rfarrah7","password":"480Rf57"},
{"email":"lbaldung8@archive.org","username":"molerenshaw8","password":"IbKzeU44I63"},
{"email":"dcorter9@nbcnews.com","username":"ncopo9","password":"RKb694g2kCyr"},
{"email":"joxtona@angelfire.com","username":"raddiea","password":"Mlhkht"},
{"email":"rocrianeb@house.gov","username":"bantonuttib","password":"ahgaJ3A"},
{"email":"aaustinc@vk.com","username":"cbonsalec","password":"j6n3VD6w3s"},
{"email":"bosesnaned@hubpages.com","username":"brommed","password":"woq3a3Dd"},
{"email":"lwaggette@omniture.com","username":"nhousecrafte","password":"c0rEkvIUJj"},
{"email":"avinckf@facebook.com","username":"gjacmardf","password":"xt46Jsou7P"},
{"email":"abrouneg@booking.com","username":"ljohnceyg","password":"mG5zm7u"},
{"email":"msimoh@webnode.com","username":"jvlasinh","password":"asHCw8KN67Wy"},
{"email":"cconklini@facebook.com","username":"ecanbyi","password":"64HNEJ05r65x"},
{"email":"ahucj@cbslocal.com","username":"akelshawj","password":"GRcfLbFnyE"},
{"email":"smussonk@canalblog.com","username":"mtennetk","password":"I26sFJXV9om"},
{"email":"ntrewhittl@about.me","username":"ahilliaml","password":"JRXIoISrUOLz"},
{"email":"jdodlem@latimes.com","username":"irushbrookem","password":"ZZrb48JhGBQ"},
{"email":"swrathalln@pen.io","username":"sphilippaultn","password":"oSg4TmQ"},
{"email":"mceeleyo@mac.com","username":"celvyo","password":"63isDMzYbvT"},
{"email":"fkighlyp@baidu.com","username":"hrameyp","password":"7FqYEfCCCzR"},
{"email":"strudgianq@mysql.com","username":"ecavilleq","password":"5u4V0mzSIxjQ"},
{"email":"gcalfer@who.int","username":"rhindmoorr","password":"zBwfFTX4G"},
{"email":"sherniks@acquirethisname.com","username":"bstronghills","password":"hFEsCVGWBzd"},
{"email":"evostt@livejournal.com","username":"skarpinskit","password":"xDX7Jx2eyUG"},
{"email":"kbenbowu@google.de","username":"aromeu","password":"ZgOn2WZPiIs"},
{"email":"lparrissv@bing.com","username":"ndickinsonv","password":"pxCKmoQ7xb"},
{"email":"gghestw@1688.com","username":"abutew","password":"dDBJEZlZfp"},
{"email":"ggilbyx@salon.com","username":"nbrazx","password":"1axGwBj76pS"},
{"email":"agregsony@uol.com.br","username":"nsimioliy","password":"wJOcDX"},
{"email":"pchaffynz@uiuc.edu","username":"pheskeyz","password":"KMR3iMtI5itk"},
{"email":"pcasari10@gizmodo.com","username":"jsaiz10","password":"eFYuEE4YgZE"},
{"email":"rhasker11@thetimes.co.uk","username":"mtredget11","password":"860lXb"},
{"email":"uzisneros12@tmall.com","username":"lspellworth12","password":"A0Lp8w0FPX1"},
{"email":"tdinneen13@jalbum.net","username":"ggregoletti13","password":"reBWC8"},
{"email":"cmacgall14@skype.com","username":"aoene14","password":"CWJN2jJ74fYt"},
{"email":"rgherardelli15@npr.org","username":"rfriskey15","password":"VXGqVBbr"},
{"email":"bsam16@sbwire.com","username":"bbowland16","password":"SMTzL3"},
{"email":"lblizard17@adobe.com","username":"cambrogini17","password":"nXQIC3Uk"},
{"email":"mzollner18@fda.gov","username":"dassard18","password":"7blpTUqtYcJ"},
{"email":"pcownden19@alexa.com","username":"aburnes19","password":"Ja6CuwjM7R"},
{"email":"kquantrill1a@mapy.cz","username":"gwanka1a","password":"bwmogny6VRRX"},
{"email":"bmckinty1b@symantec.com","username":"rjelley1b","password":"p8JMoBgGZjr"},
{"email":"lwillatt1c@cbsnews.com","username":"tmathieu1c","password":"3LDRMhoUf"},
{"email":"chulle1d@bbc.co.uk","username":"aecclestone1d","password":"Aw3psJhh"}];

// const parseSeedData = (seedData) => {
//   const parsedJSON = seedData.map((JSONobject) => {
//     return JSON.parse(`'${JSONobject}'`);
//   });
//   return parsedJSON;
// }

const jsonobjtest = { "name":"John", "age":30, "city":"New York"};
console.log(JSON.parse(JSON.stringify(jsonobjtest)))
